-- ============================================================================
-- V870 — TCF CO B2 — lot 08 (thème : présentation d'un produit ou d'une innovation)
-- ----------------------------------------------------------------------------
-- Brouillons audio CO (B2), format C : monologue expositif long (~120-200 mots)
-- + question implicite (apport principal, idée principale, intention du
-- locuteur, conséquence non dite). Table audio_question_draft.
-- status='TEXT_VALIDATED', colonnes audio NULL (remplies par le batch admin
-- Azure). Contenu 100% original, produits et innovateurs inventés.
-- ============================================================================

INSERT INTO audio_question_draft
  (id, difficulty, competence_code, theme_id, transcript_text, ssml_text, statement, explanation,
   choices, voice_recommended, status, audio_url, audio_duration_sec, audio_voice_used,
   audio_generated_at, batch_id, created_at, audio_validated_at, audio_validated_by,
   rejection_reason)
VALUES
  ('66666666-c008-1000-0000-000000000001', 'B2', 'co_document_question', '22222222-0000-0000-0000-000000000001',
   'Écoutez le document puis la question. Choisissez la bonne réponse.

[Femme] Bonjour, je m''appelle Wei Lin, ingénieure agronome, et je viens vous présenter Ruchéo, un capteur que nous avons mis au point à Avignon après trois ans de recherche. Chaque ouverture d''une ruche est un stress considérable pour la colonie : la température chute, les abeilles s''agitent, la reine interrompt parfois sa ponte. Or, pour vérifier l''état d''une colonie, l''apiculteur n''avait jusqu''ici pas d''autre choix que de soulever les cadres. Ruchéo change la donne. Glissé sous le toit de la ruche, il mesure en continu la température, l''humidité, le poids et même la fréquence des vibrations, puis envoie ces données sur le téléphone de l''apiculteur. Une colonie qui s''affaiblit se repère ainsi des semaines plus tôt, sans déranger personne. Je précise que Ruchéo ne remplace pas l''œil du professionnel : quand l''alerte sonne, c''est bien lui qui intervient. Notre capteur lui évite simplement d''ouvrir cent ruches pour en trouver trois en difficulté.

Quel est l''apport principal de ce capteur ?

A. Augmenter la production de miel des ruches équipées.
B. Permettre de surveiller l''état des colonies sans ouvrir les ruches.
C. Remplacer l''intervention de l''apiculteur auprès des colonies.
D. Mesurer la qualité du miel produit par chaque colonie.',
   '<speak version="1.0" xml:lang="fr-FR"><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">Écoutez le document puis la question. Choisissez la bonne réponse.</prosody></voice><break time="1500ms"/><voice name="fr-FR-VivienneNeural"><prosody rate="1.0">Bonjour, je m''appelle Wei Lin, ingénieure agronome, et je viens vous présenter Ruchéo, un capteur que nous avons mis au point à Avignon après trois ans de recherche. Chaque ouverture d''une ruche est un stress considérable pour la colonie : la température chute, les abeilles s''agitent, la reine interrompt parfois sa ponte. Or, pour vérifier l''état d''une colonie, l''apiculteur n''avait jusqu''ici pas d''autre choix que de soulever les cadres. Ruchéo change la donne. Glissé sous le toit de la ruche, il mesure en continu la température, l''humidité, le poids et même la fréquence des vibrations, puis envoie ces données sur le téléphone de l''apiculteur. Une colonie qui s''affaiblit se repère ainsi des semaines plus tôt, sans déranger personne. Je précise que Ruchéo ne remplace pas l''œil du professionnel : quand l''alerte sonne, c''est bien lui qui intervient. Notre capteur lui évite simplement d''ouvrir cent ruches pour en trouver trois en difficulté.</prosody></voice><break time="1000ms"/><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">Quel est l''apport principal de ce capteur ?</prosody></voice><break time="1000ms"/><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">A.<break time="300ms"/>Augmenter la production de miel des ruches équipées.<break time="700ms"/>B.<break time="300ms"/>Permettre de surveiller l''état des colonies sans ouvrir les ruches.<break time="700ms"/>C.<break time="300ms"/>Remplacer l''intervention de l''apiculteur auprès des colonies.<break time="700ms"/>D.<break time="300ms"/>Mesurer la qualité du miel produit par chaque colonie.</prosody></voice></speak>',
   'Écoutez le document sonore, puis choisissez la bonne réponse parmi les propositions A, B, C ou D.',
   'Le monologue oppose la méthode ancienne (soulever les cadres, stresser la colonie) et la promesse du capteur : des données envoyées en continu, une colonie faible repérée « sans déranger personne ». Il faut **inférer l''apport principal à partir des exemples concrets** — mécanisme B2 de synthèse de l''idée principale. B reformule exactement cette surveillance sans ouverture. A invente une **conséquence jamais affirmée** : la production de miel n''est pas évoquée dans le document. C contredit la mise au point finale « Ruchéo ne remplace pas l''œil du professionnel » : c''est l''apiculteur qui intervient quand l''alerte sonne. D déforme un détail technique : le capteur mesure température, humidité, poids et vibrations, jamais la qualité du miel.',
   '[{"label": "A", "is_correct": false, "display_order": 1}, {"label": "B", "is_correct": true, "display_order": 2}, {"label": "C", "is_correct": false, "display_order": 3}, {"label": "D", "is_correct": false, "display_order": 4}]',
   'fr-FR-VivienneNeural', 'TEXT_VALIDATED',
   NULL, NULL, NULL, NULL, NULL,
   '2026-06-07 12:00:00+02', NULL, NULL, NULL),

  ('66666666-c008-1000-0000-000000000002', 'B2', 'co_document_question', '22222222-0000-0000-0000-000000000001',
   'Écoutez le document puis la question. Choisissez la bonne réponse.

[Homme] Bonjour à tous, Tomas Ferreira, cofondateur de Pelliroc, à La Rochelle. Notre région produit chaque année des milliers de tonnes de coquilles d''huîtres qui finissent broyées en bord de route ou enfouies, faute de mieux. De l''autre côté, le bâtiment cherche désespérément des isolants moins polluants que les mousses issues du pétrole. Nous avons passé quatre ans à relier ces deux problèmes. Pelliroc est un enduit isolant composé à quatre-vingts pour cent de poudre de coquilles, mélangée à un liant à base de chaux. Appliqué sur un mur intérieur, il améliore l''isolation thermique et régule naturellement l''humidité. Soyons honnêtes : il n''égale pas encore les performances des isolants épais, et nous le réservons pour l''instant à la rénovation des bâtiments anciens. Mais chaque chantier réalisé, c''est plusieurs tonnes de coquilles détournées de la décharge. Nous ne posons pas l''enduit nous-mêmes : nous le fabriquons et nous formons les artisans qui souhaitent l''utiliser.

Quelle est l''idée principale de cette présentation ?

A. Les coquilles d''huîtres sont difficiles à recycler dans la région.
B. Cet enduit isole mieux que tous les matériaux du marché.
C. L''entreprise rénove elle-même les bâtiments anciens du littoral.
D. L''entreprise transforme un déchet local en matériau d''isolation.',
   '<speak version="1.0" xml:lang="fr-FR"><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">Écoutez le document puis la question. Choisissez la bonne réponse.</prosody></voice><break time="1500ms"/><voice name="fr-FR-HenriNeural"><prosody rate="1.0">Bonjour à tous, Tomas Ferreira, cofondateur de Pelliroc, à La Rochelle. Notre région produit chaque année des milliers de tonnes de coquilles d''huîtres qui finissent broyées en bord de route ou enfouies, faute de mieux. De l''autre côté, le bâtiment cherche désespérément des isolants moins polluants que les mousses issues du pétrole. Nous avons passé quatre ans à relier ces deux problèmes. Pelliroc est un enduit isolant composé à quatre-vingts pour cent de poudre de coquilles, mélangée à un liant à base de chaux. Appliqué sur un mur intérieur, il améliore l''isolation thermique et régule naturellement l''humidité. Soyons honnêtes : il n''égale pas encore les performances des isolants épais, et nous le réservons pour l''instant à la rénovation des bâtiments anciens. Mais chaque chantier réalisé, c''est plusieurs tonnes de coquilles détournées de la décharge. Nous ne posons pas l''enduit nous-mêmes : nous le fabriquons et nous formons les artisans qui souhaitent l''utiliser.</prosody></voice><break time="1000ms"/><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">Quelle est l''idée principale de cette présentation ?</prosody></voice><break time="1000ms"/><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">A.<break time="300ms"/>Les coquilles d''huîtres sont difficiles à recycler dans la région.<break time="700ms"/>B.<break time="300ms"/>Cet enduit isole mieux que tous les matériaux du marché.<break time="700ms"/>C.<break time="300ms"/>L''entreprise rénove elle-même les bâtiments anciens du littoral.<break time="700ms"/>D.<break time="300ms"/>L''entreprise transforme un déchet local en matériau d''isolation.</prosody></voice></speak>',
   'Écoutez le document sonore, puis choisissez la bonne réponse parmi les propositions A, B, C ou D.',
   'Tomas relie deux problèmes (un déchet coquillier sans débouché, des isolants polluants) et conclut sur « plusieurs tonnes de coquilles détournées de la décharge » : D synthétise ce propos — valoriser un déchet local en isolant. Mécanisme B2 : distinguer **le thème de départ et le propos global**. A reprend le **constat initial** (le contexte) et le fait passer pour l''idée principale : c''est précisément le problème que Pelliroc résout, pas le message du document. B contredit l''aveu de modestie « il n''égale pas encore les performances des isolants épais » — piège sur la **surenchère par rapport au texte**. C est explicitement niée : « nous ne posons pas l''enduit nous-mêmes », l''entreprise fabrique et forme les artisans.',
   '[{"label": "A", "is_correct": false, "display_order": 1}, {"label": "B", "is_correct": false, "display_order": 2}, {"label": "C", "is_correct": false, "display_order": 3}, {"label": "D", "is_correct": true, "display_order": 4}]',
   'fr-FR-HenriNeural', 'TEXT_VALIDATED',
   NULL, NULL, NULL, NULL, NULL,
   '2026-06-07 12:00:00+02', NULL, NULL, NULL),

  ('66666666-c008-1000-0000-000000000003', 'B2', 'co_document_question', '22222222-0000-0000-0000-000000000001',
   'Écoutez le document puis la question. Choisissez la bonne réponse.

[Femme] Je m''appelle Aïcha Benkacem, je suis orthophoniste à Lyon, et j''ai conçu Vocalise avec deux développeurs. Après un accident vasculaire cérébral, beaucoup de patients perdent partiellement la parole. La rééducation fonctionne, mais elle exige une répétition quotidienne, alors que les séances chez l''orthophoniste n''ont lieu qu''une ou deux fois par semaine. Entre deux rendez-vous, les patients se retrouvent seuls, et les progrès s''essoufflent. Vocalise comble précisément ce vide. Chaque soir, l''application propose au patient une série d''exercices choisis par son orthophoniste : répéter des sons, nommer des images, reconstruire des phrases. Elle écoute les réponses, encourage, adapte la difficulté, puis transmet un compte rendu au thérapeute, qui ajuste la séance suivante. Je tiens à être claire : aucune application ne remplacera la relation avec un professionnel, et Vocalise ne pose aucun diagnostic. Elle prolonge le travail commencé au cabinet, tous les jours, à domicile. Les premiers résultats montrent des progrès nettement plus réguliers chez les patients qui l''utilisent.

Quel est le rôle de cette application ?

A. Prolonger la rééducation à domicile entre les séances d''orthophonie.
B. Remplacer les séances chez l''orthophoniste pour les patients éloignés.
C. Détecter les accidents vasculaires cérébraux chez les personnes à risque.
D. Mettre en relation les patients avec des orthophonistes disponibles.',
   '<speak version="1.0" xml:lang="fr-FR"><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">Écoutez le document puis la question. Choisissez la bonne réponse.</prosody></voice><break time="1500ms"/><voice name="fr-FR-VivienneNeural"><prosody rate="1.0">Je m''appelle Aïcha Benkacem, je suis orthophoniste à Lyon, et j''ai conçu Vocalise avec deux développeurs. Après un accident vasculaire cérébral, beaucoup de patients perdent partiellement la parole. La rééducation fonctionne, mais elle exige une répétition quotidienne, alors que les séances chez l''orthophoniste n''ont lieu qu''une ou deux fois par semaine. Entre deux rendez-vous, les patients se retrouvent seuls, et les progrès s''essoufflent. Vocalise comble précisément ce vide. Chaque soir, l''application propose au patient une série d''exercices choisis par son orthophoniste : répéter des sons, nommer des images, reconstruire des phrases. Elle écoute les réponses, encourage, adapte la difficulté, puis transmet un compte rendu au thérapeute, qui ajuste la séance suivante. Je tiens à être claire : aucune application ne remplacera la relation avec un professionnel, et Vocalise ne pose aucun diagnostic. Elle prolonge le travail commencé au cabinet, tous les jours, à domicile. Les premiers résultats montrent des progrès nettement plus réguliers chez les patients qui l''utilisent.</prosody></voice><break time="1000ms"/><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">Quel est le rôle de cette application ?</prosody></voice><break time="1000ms"/><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">A.<break time="300ms"/>Prolonger la rééducation à domicile entre les séances d''orthophonie.<break time="700ms"/>B.<break time="300ms"/>Remplacer les séances chez l''orthophoniste pour les patients éloignés.<break time="700ms"/>C.<break time="300ms"/>Détecter les accidents vasculaires cérébraux chez les personnes à risque.<break time="700ms"/>D.<break time="300ms"/>Mettre en relation les patients avec des orthophonistes disponibles.</prosody></voice></speak>',
   'Écoutez le document sonore, puis choisissez la bonne réponse parmi les propositions A, B, C ou D.',
   'Aïcha pose un manque (« entre deux rendez-vous, les patients se retrouvent seuls »), puis le résout : « Vocalise comble précisément ce vide » et « elle prolonge le travail commencé au cabinet ». A reformule cette **fonction de complément entre les séances** — mécanisme B2 d''identification du rôle à partir du problème résolu. B est explicitement écartée : « aucune application ne remplacera la relation avec un professionnel » — piège classique entre **compléter et remplacer**. C contredit « Vocalise ne pose aucun diagnostic » : l''AVC est le contexte du document, pas ce que l''application détecte. D invente un service de mise en relation : le patient a déjà son orthophoniste, l''application ne fait que transmettre un compte rendu au thérapeute existant.',
   '[{"label": "A", "is_correct": true, "display_order": 1}, {"label": "B", "is_correct": false, "display_order": 2}, {"label": "C", "is_correct": false, "display_order": 3}, {"label": "D", "is_correct": false, "display_order": 4}]',
   'fr-FR-VivienneNeural', 'TEXT_VALIDATED',
   NULL, NULL, NULL, NULL, NULL,
   '2026-06-07 12:00:00+02', NULL, NULL, NULL),

  ('66666666-c008-1000-0000-000000000004', 'B2', 'co_document_question', '22222222-0000-0000-0000-000000000001',
   'Écoutez le document puis la question. Choisissez la bonne réponse.

[Homme] Bonjour, Sergio Almeida, fondateur de l''atelier Caribou, à Bordeaux. Notre produit est une remorque électrique qui s''attache à n''importe quel vélo et transporte jusqu''à cent cinquante kilos de matériel. À première vue, ce n''est qu''une remorque. En réalité, elle répond à un problème très concret : dans les centres-villes, circuler et stationner avec une camionnette devient un casse-tête, entre zones à faibles émissions, rues piétonnes et amendes. Un plombier qui perd quarante minutes à chercher une place perd aussi un client. Avec Caribou, ses outils, ses pièces et même un chauffe-eau tiennent dans des caissons modulables, verrouillables, protégés de la pluie. Le moteur électrique de la remorque pousse l''ensemble, si bien qu''on pédale sans effort, même en côte. Nous ne prétendons pas remplacer la camionnette pour les gros chantiers en périphérie. Mais pour les interventions quotidiennes en ville, nos cent premiers clients le confirment : ils gagnent du temps, économisent du carburant, et retrouvent des clients qu''ils refusaient autrefois.

Pourquoi cette remorque intéresse-t-elle les artisans ?

A. Elle remplace la camionnette sur tous leurs chantiers.
B. Elle leur évite tout effort physique grâce à son moteur.
C. Elle leur permet d''intervenir en ville sans les contraintes de la camionnette.
D. Elle leur sert à transporter leurs clients dans le centre-ville.',
   '<speak version="1.0" xml:lang="fr-FR"><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">Écoutez le document puis la question. Choisissez la bonne réponse.</prosody></voice><break time="1500ms"/><voice name="fr-FR-HenriNeural"><prosody rate="1.0">Bonjour, Sergio Almeida, fondateur de l''atelier Caribou, à Bordeaux. Notre produit est une remorque électrique qui s''attache à n''importe quel vélo et transporte jusqu''à cent cinquante kilos de matériel. À première vue, ce n''est qu''une remorque. En réalité, elle répond à un problème très concret : dans les centres-villes, circuler et stationner avec une camionnette devient un casse-tête, entre zones à faibles émissions, rues piétonnes et amendes. Un plombier qui perd quarante minutes à chercher une place perd aussi un client. Avec Caribou, ses outils, ses pièces et même un chauffe-eau tiennent dans des caissons modulables, verrouillables, protégés de la pluie. Le moteur électrique de la remorque pousse l''ensemble, si bien qu''on pédale sans effort, même en côte. Nous ne prétendons pas remplacer la camionnette pour les gros chantiers en périphérie. Mais pour les interventions quotidiennes en ville, nos cent premiers clients le confirment : ils gagnent du temps, économisent du carburant, et retrouvent des clients qu''ils refusaient autrefois.</prosody></voice><break time="1000ms"/><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">Pourquoi cette remorque intéresse-t-elle les artisans ?</prosody></voice><break time="1000ms"/><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">A.<break time="300ms"/>Elle remplace la camionnette sur tous leurs chantiers.<break time="700ms"/>B.<break time="300ms"/>Elle leur évite tout effort physique grâce à son moteur.<break time="700ms"/>C.<break time="300ms"/>Elle leur permet d''intervenir en ville sans les contraintes de la camionnette.<break time="700ms"/>D.<break time="300ms"/>Elle leur sert à transporter leurs clients dans le centre-ville.</prosody></voice></speak>',
   'Écoutez le document sonore, puis choisissez la bonne réponse parmi les propositions A, B, C ou D.',
   'Le document part du problème (zones à faibles émissions, stationnement, amendes : la camionnette devient « un casse-tête » en ville) et montre la solution : gagner du temps et retrouver des clients en centre-ville. C reformule cette **conséquence pratique non formulée en une phrase** — inférence B2 entre problème posé et bénéfice réel. A généralise abusivement : Sergio précise « nous ne prétendons pas remplacer la camionnette pour les gros chantiers en périphérie » — piège du **« tous » contredit par une restriction explicite**. B élève un **détail secondaire** (le moteur qui aide à pédaler « sans effort ») au rang de raison principale : c''est un moyen, pas l''intérêt central. D est un contresens : la remorque transporte du matériel (outils, pièces, chauffe-eau), jamais des personnes.',
   '[{"label": "A", "is_correct": false, "display_order": 1}, {"label": "B", "is_correct": false, "display_order": 2}, {"label": "C", "is_correct": true, "display_order": 3}, {"label": "D", "is_correct": false, "display_order": 4}]',
   'fr-FR-HenriNeural', 'TEXT_VALIDATED',
   NULL, NULL, NULL, NULL, NULL,
   '2026-06-07 12:00:00+02', NULL, NULL, NULL),

  ('66666666-c008-1000-0000-000000000005', 'B2', 'co_document_question', '22222222-0000-0000-0000-000000000001',
   'Écoutez le document puis la question. Choisissez la bonne réponse.

[Femme] Je suis Mariam Diop, créatrice textile, et je présente aujourd''hui Thermalin, un tissu développé pendant cinq ans dans notre atelier de Lille. On trouve déjà des vestes chauffantes dans le commerce, mais elles embarquent des fils électriques et une batterie : lourdes, fragiles, impossibles à laver normalement. Nous avons pris le chemin inverse. Thermalin ne contient aucun composant électronique. Son secret tient dans la structure de la fibre : un lin cultivé dans les Hauts-de-France, tissé en double épaisseur, dont les microcanaux emprisonnent l''air quand il fait froid et l''évacuent quand le corps chauffe. Résultat, le même vêtement accompagne aussi bien une matinée d''hiver qu''un après-midi de printemps. Le tissu se lave en machine, se répare comme n''importe quel lainage, et se composte en fin de vie. Nous ne fabriquons pas de vêtements nous-mêmes : nous vendons le tissu au mètre à des marques françaises. Trois d''entre elles sortiront leur première collection Thermalin au printemps prochain.

Qu''est-ce qui distingue ce tissu des produits existants ?

A. Il chauffe grâce à une batterie plus légère que les autres.
B. Il régule la température sans aucun dispositif électronique.
C. Il est vendu sous forme de vêtements prêts à porter.
D. Il est le premier tissu au monde fabriqué à partir de lin.',
   '<speak version="1.0" xml:lang="fr-FR"><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">Écoutez le document puis la question. Choisissez la bonne réponse.</prosody></voice><break time="1500ms"/><voice name="fr-FR-VivienneNeural"><prosody rate="1.0">Je suis Mariam Diop, créatrice textile, et je présente aujourd''hui Thermalin, un tissu développé pendant cinq ans dans notre atelier de Lille. On trouve déjà des vestes chauffantes dans le commerce, mais elles embarquent des fils électriques et une batterie : lourdes, fragiles, impossibles à laver normalement. Nous avons pris le chemin inverse. Thermalin ne contient aucun composant électronique. Son secret tient dans la structure de la fibre : un lin cultivé dans les Hauts-de-France, tissé en double épaisseur, dont les microcanaux emprisonnent l''air quand il fait froid et l''évacuent quand le corps chauffe. Résultat, le même vêtement accompagne aussi bien une matinée d''hiver qu''un après-midi de printemps. Le tissu se lave en machine, se répare comme n''importe quel lainage, et se composte en fin de vie. Nous ne fabriquons pas de vêtements nous-mêmes : nous vendons le tissu au mètre à des marques françaises. Trois d''entre elles sortiront leur première collection Thermalin au printemps prochain.</prosody></voice><break time="1000ms"/><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">Qu''est-ce qui distingue ce tissu des produits existants ?</prosody></voice><break time="1000ms"/><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">A.<break time="300ms"/>Il chauffe grâce à une batterie plus légère que les autres.<break time="700ms"/>B.<break time="300ms"/>Il régule la température sans aucun dispositif électronique.<break time="700ms"/>C.<break time="300ms"/>Il est vendu sous forme de vêtements prêts à porter.<break time="700ms"/>D.<break time="300ms"/>Il est le premier tissu au monde fabriqué à partir de lin.</prosody></voice></speak>',
   'Écoutez le document sonore, puis choisissez la bonne réponse parmi les propositions A, B, C ou D.',
   'La structure du document est une **opposition** : les vestes chauffantes existantes (fils électriques, batterie) contre « le chemin inverse » — « Thermalin ne contient aucun composant électronique », la régulation vient de la structure de la fibre. B reformule cette spécificité, qu''il faut dégager du **contraste construit par la locutrice** (mécanisme B2 de repérage de l''opposition argumentative). A attribue à Thermalin précisément ce qu''il rejette : la batterie appartient aux produits concurrents critiqués — piège d''**inversion des deux termes de la comparaison**. C contredit « nous ne fabriquons pas de vêtements nous-mêmes : nous vendons le tissu au mètre ». D déforme l''innovation : le lin n''est pas nouveau, c''est son tissage en double épaisseur à microcanaux qui l''est ; rien ne dit qu''il s''agit du « premier » tissu en lin.',
   '[{"label": "A", "is_correct": false, "display_order": 1}, {"label": "B", "is_correct": true, "display_order": 2}, {"label": "C", "is_correct": false, "display_order": 3}, {"label": "D", "is_correct": false, "display_order": 4}]',
   'fr-FR-VivienneNeural', 'TEXT_VALIDATED',
   NULL, NULL, NULL, NULL, NULL,
   '2026-06-07 12:00:00+02', NULL, NULL, NULL),

  ('66666666-c008-1000-0000-000000000006', 'B2', 'co_document_question', '22222222-0000-0000-0000-000000000001',
   'Écoutez le document puis la question. Choisissez la bonne réponse.

[Homme] Bonjour, Anh Nguyen, ingénieur agroalimentaire et cofondateur de Lentia, près de Toulouse. Notre innovation tient en un sac de farine. Une farine de lentilles vertes, cultivées à moins de cent kilomètres de notre moulin, que nous avons mis trois ans à rendre panifiable. Car le problème était là : la lentille est deux fois plus riche en protéines que le blé, mais sa farine brute donne un pain compact, au goût trop marqué. Notre procédé de torréfaction douce, que nous avons breveté, adoucit ce goût et permet d''incorporer jusqu''à trente pour cent de lentille dans une baguette sans changer les gestes du boulanger. Soyons précis : nous ne demandons à personne d''abandonner le blé. Nous proposons un complément qui enrichit le pain en protéines végétales, tout en offrant un débouché stable aux producteurs locaux de légumineuses. Quarante boulangeries de la région travaillent déjà avec nous, et une grande enseigne teste notre farine dans ses fournils depuis janvier.

En quoi consiste l''innovation présentée ?

A. Une nouvelle variété de lentilles plus riche en protéines.
B. Un pain fabriqué sans aucune farine de blé.
C. Une boulangerie spécialisée dans le pain de lentilles.
D. Un procédé qui rend la farine de lentilles utilisable en boulangerie.',
   '<speak version="1.0" xml:lang="fr-FR"><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">Écoutez le document puis la question. Choisissez la bonne réponse.</prosody></voice><break time="1500ms"/><voice name="fr-FR-HenriNeural"><prosody rate="1.0">Bonjour, Anh Nguyen, ingénieur agroalimentaire et cofondateur de Lentia, près de Toulouse. Notre innovation tient en un sac de farine. Une farine de lentilles vertes, cultivées à moins de cent kilomètres de notre moulin, que nous avons mis trois ans à rendre panifiable. Car le problème était là : la lentille est deux fois plus riche en protéines que le blé, mais sa farine brute donne un pain compact, au goût trop marqué. Notre procédé de torréfaction douce, que nous avons breveté, adoucit ce goût et permet d''incorporer jusqu''à trente pour cent de lentille dans une baguette sans changer les gestes du boulanger. Soyons précis : nous ne demandons à personne d''abandonner le blé. Nous proposons un complément qui enrichit le pain en protéines végétales, tout en offrant un débouché stable aux producteurs locaux de légumineuses. Quarante boulangeries de la région travaillent déjà avec nous, et une grande enseigne teste notre farine dans ses fournils depuis janvier.</prosody></voice><break time="1000ms"/><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">En quoi consiste l''innovation présentée ?</prosody></voice><break time="1000ms"/><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">A.<break time="300ms"/>Une nouvelle variété de lentilles plus riche en protéines.<break time="700ms"/>B.<break time="300ms"/>Un pain fabriqué sans aucune farine de blé.<break time="700ms"/>C.<break time="300ms"/>Une boulangerie spécialisée dans le pain de lentilles.<break time="700ms"/>D.<break time="300ms"/>Un procédé qui rend la farine de lentilles utilisable en boulangerie.</prosody></voice></speak>',
   'Écoutez le document sonore, puis choisissez la bonne réponse parmi les propositions A, B, C ou D.',
   'Il faut **localiser où se situe exactement la nouveauté** : la lentille et sa richesse en protéines existaient déjà, l''obstacle était la farine brute (« pain compact, au goût trop marqué »), et la levée de cet obstacle est « notre procédé de torréfaction douce, que nous avons breveté » — D le synthétise. Mécanisme B2 : distinguer **le matériau (connu) du procédé (innovant)**. A déplace l''innovation sur la plante : sa teneur en protéines est présentée comme une propriété déjà connue, pas comme une création de Lentia. B contredit « nous ne demandons à personne d''abandonner le blé » et la limite des trente pour cent d''incorporation. C inverse les acteurs : Lentia est un moulin qui vend sa farine ; les quarante boulangeries sont ses clientes, pas son métier.',
   '[{"label": "A", "is_correct": false, "display_order": 1}, {"label": "B", "is_correct": false, "display_order": 2}, {"label": "C", "is_correct": false, "display_order": 3}, {"label": "D", "is_correct": true, "display_order": 4}]',
   'fr-FR-HenriNeural', 'TEXT_VALIDATED',
   NULL, NULL, NULL, NULL, NULL,
   '2026-06-07 12:00:00+02', NULL, NULL, NULL),

  ('66666666-c008-1000-0000-000000000007', 'B2', 'co_document_question', '22222222-0000-0000-0000-000000000001',
   'Écoutez le document puis la question. Choisissez la bonne réponse.

[Femme] Bonjour, je m''appelle Nadia Cherif et j''ai fondé Sentinelle à Strasbourg, après la chute de ma propre grand-mère, restée au sol toute une nuit sans pouvoir alerter personne. Beaucoup de familles, face à ce risque, installent des caméras ; la plupart des aînés les vivent comme une intrusion et finissent par les débrancher. Sentinelle repose sur une idée différente : un tapis discret, posé dans le couloir ou près du lit, qui analyse la manière de marcher. Aucune image, aucun micro. Si la personne tombe, ou si sa démarche change brutalement au fil des jours, le tapis envoie une alerte au proche ou au médecin désigné. Soyons clairs : Sentinelle ne fait pas le ménage, ne porte pas les courses, ne remplace ni l''aide à domicile ni la visite du dimanche. Ce que nous vendons, au fond, ce n''est pas un tapis : c''est la possibilité de vieillir chez soi sans être observé, tout en sachant que, le jour où tout bascule, quelqu''un le saura dans la minute.

Quelle est l''intention de la fondatrice avec ce produit ?

A. Sécuriser le maintien à domicile des aînés tout en respectant leur intimité.
B. Surveiller les personnes âgées grâce à des caméras discrètes.
C. Remplacer les services d''aide à domicile auprès des aînés.
D. Vendre des tapis décoratifs adaptés aux personnes âgées.',
   '<speak version="1.0" xml:lang="fr-FR"><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">Écoutez le document puis la question. Choisissez la bonne réponse.</prosody></voice><break time="1500ms"/><voice name="fr-FR-VivienneNeural"><prosody rate="1.0">Bonjour, je m''appelle Nadia Cherif et j''ai fondé Sentinelle à Strasbourg, après la chute de ma propre grand-mère, restée au sol toute une nuit sans pouvoir alerter personne. Beaucoup de familles, face à ce risque, installent des caméras ; la plupart des aînés les vivent comme une intrusion et finissent par les débrancher. Sentinelle repose sur une idée différente : un tapis discret, posé dans le couloir ou près du lit, qui analyse la manière de marcher. Aucune image, aucun micro. Si la personne tombe, ou si sa démarche change brutalement au fil des jours, le tapis envoie une alerte au proche ou au médecin désigné. Soyons clairs : Sentinelle ne fait pas le ménage, ne porte pas les courses, ne remplace ni l''aide à domicile ni la visite du dimanche. Ce que nous vendons, au fond, ce n''est pas un tapis : c''est la possibilité de vieillir chez soi sans être observé, tout en sachant que, le jour où tout bascule, quelqu''un le saura dans la minute.</prosody></voice><break time="1000ms"/><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">Quelle est l''intention de la fondatrice avec ce produit ?</prosody></voice><break time="1000ms"/><voice name="fr-FR-DeniseNeural"><prosody rate="0.95">A.<break time="300ms"/>Sécuriser le maintien à domicile des aînés tout en respectant leur intimité.<break time="700ms"/>B.<break time="300ms"/>Surveiller les personnes âgées grâce à des caméras discrètes.<break time="700ms"/>C.<break time="300ms"/>Remplacer les services d''aide à domicile auprès des aînés.<break time="700ms"/>D.<break time="300ms"/>Vendre des tapis décoratifs adaptés aux personnes âgées.</prosody></voice></speak>',
   'Écoutez le document sonore, puis choisissez la bonne réponse parmi les propositions A, B, C ou D.',
   'L''intention est condensée dans la chute du monologue : « ce que nous vendons, ce n''est pas un tapis, c''est la possibilité de vieillir chez soi sans être observé » tout en étant secouru immédiatement. A reformule ce double objectif (sécurité + intimité) — mécanisme B2 d''**inférence de l''intention du locuteur** au-delà de l''objet vendu. B attribue à Sentinelle la solution que Nadia critique : les caméras, vécues « comme une intrusion », et le tapis n''enregistre « aucune image, aucun micro » — piège d''**inversion entre le produit et son repoussoir**. C contredit l''énumération explicite : Sentinelle « ne remplace ni l''aide à domicile ni la visite du dimanche ». D s''arrête au **thème de surface** (un tapis) en ignorant le propos : la fondatrice précise justement que le tapis n''est pas ce qu''elle vend « au fond ».',
   '[{"label": "A", "is_correct": true, "display_order": 1}, {"label": "B", "is_correct": false, "display_order": 2}, {"label": "C", "is_correct": false, "display_order": 3}, {"label": "D", "is_correct": false, "display_order": 4}]',
   'fr-FR-VivienneNeural', 'TEXT_VALIDATED',
   NULL, NULL, NULL, NULL, NULL,
   '2026-06-07 12:00:00+02', NULL, NULL, NULL);

-- ============================================================================
-- CHECKLIST (contrôles passés avant livraison)
-- ----------------------------------------------------------------------------
-- [x] 7 items, UUID déterministes 66666666-c008-1000-0000-000000000001..07.
-- [x] Format C exclusif (co_document_question), monologue expositif long :
--     longueurs comptées = 149 / 150 / 156 / 157 / 153 / 155 / 164 mots
--     (toutes dans la fourchette 120-200 mots B2).
-- [x] Thème unique « présentation d''un produit ou d''une innovation »,
--     7 produits inventés tous différents : capteur connecté pour ruches
--     (Avignon), enduit isolant en coquilles d''huîtres (La Rochelle),
--     application de rééducation orthophonique (Lyon), remorque vélo
--     électrique pour artisans (Bordeaux), tissu thermorégulateur en lin
--     (Lille), farine de lentilles panifiable (Toulouse), tapis détecteur
--     de chutes (Strasbourg). Prénoms variés : Wei, Tomas, Aïcha, Sergio,
--     Mariam, Anh, Nadia. Aucun thème interdit du bon de commande réutilisé.
-- [x] 4 propositions / 1 correcte par item ; distribution des bonnes réponses :
--     A ×2 (items 3, 7), B ×2 (items 1, 5), C ×1 (item 4), D ×2 (items 2, 6)
--     — max 2 par lettre, 4 lettres utilisées.
-- [x] Compréhension implicite B2 : apport principal, idée principale,
--     rôle/fonction, conséquence non dite, intention du locuteur ;
--     distracteurs tous plausibles (thème vs propos, détail secondaire vs
--     idée principale, inversion produit/repoussoir, inversion des acteurs).
-- [x] explanation ≥ 80 caractères, justifie la bonne réponse + les 3
--     distracteurs, point clé en **gras**, mécanisme linguistique nommé.
-- [x] SSML équilibré (4 <voice>/4 </voice>, 4 <prosody>/4 </prosody> par item),
--     pauses conformes (1500ms / 1000ms / 700ms / 300ms), Denise (0.95) en
--     narration + Henri/Vivienne (1.0) en alternance pour le document,
--     voice_recommended = voix du document.
-- [x] status='TEXT_VALIDATED', toutes colonnes audio NULL,
--     created_at '2026-06-07 12:00:00+02'.
-- [x] Apostrophes SQL doublées partout, JSONB valide, contenu 100% original.
-- ============================================================================
