-- ============================================================================
-- V631 — TCF Structure B1
-- ----------------------------------------------------------------------------
-- 30 questions de structure niveau B1.
-- IDs générés avec gen_random_uuid().
-- ============================================================================

WITH qdata(q_ref, statement, explanation, competence_code) AS (
  VALUES
    ('q01', 'Complétez : « Si j’avais assez d’argent, je ___ un appartement plus grand. »', 'Avec « si + imparfait », la proposition principale se met au conditionnel présent : « achèterais ». On exprime une hypothèse irréelle ou peu probable dans le présent.', 'struct_si_imparfait_conditionnel'),
    ('q02', 'Complétez : « C’est la personne ___ je t’ai parlé hier. »', 'Le verbe « parler » se construit avec « de ». Le pronom relatif qui remplace un complément introduit par « de » est « dont ».', 'struct_relatif_dont_personne'),
    ('q03', 'Complétez : « Avant de sortir, elle ___ ses clés sur la table. »', 'L’action est terminée avant un autre moment du passé ou avant une action suivante. Le plus-que-parfait « avait oublié » convient pour marquer l’antériorité.', 'struct_plus_que_parfait_anterieur'),
    ('q04', 'Remplacez le complément : « Je pense souvent à mes vacances. → J’___ pense souvent. »', 'Un complément introduit par « à » peut être remplacé par le pronom « y », notamment pour une chose ou une idée.', 'struct_pronom_y_idee'),
    ('q05', 'Complétez : « Bien qu’il ___ fatigué, il continue à travailler. »', '« Bien que » est suivi du subjonctif. Avec le verbe être, on dit : « qu’il soit ».', 'struct_subjonctif_bien_que'),
    ('q06', 'Complétez : « Elle a réussi son examen ___ elle a beaucoup travaillé. »', 'On exprime ici la cause. « Parce qu’ » introduit la raison de sa réussite.', 'struct_connecteur_cause'),
    ('q07', 'Transformez au discours indirect : Il dit : « Je suis malade. »', 'Au discours indirect au présent, l’affirmation est introduite par « que ». Le pronom change selon le locuteur : « il dit qu’il est malade ».', 'struct_discours_indirect_affirmation'),
    ('q08', 'Complétez : « Nous cherchons quelqu’un qui ___ parler anglais. »', 'Après « quelqu’un qui », on emploie ici l’indicatif, car on décrit une compétence recherchée de manière générale : « peut ».', 'struct_relatif_qui_indicatif'),
    ('q09', 'Complétez : « Il est parti sans ___ au revoir. »', 'Après « sans », le verbe est à l’infinitif : « sans dire ».', 'struct_preposition_sans_infinitif'),
    ('q10', 'Complétez : « Je ne comprends pas ___ il refuse cette proposition. »', 'On interroge sur la cause : « pourquoi ». La phrase signifie : je ne comprends pas la raison de son refus.', 'struct_interrogatif_pourquoi'),
    ('q11', 'Complétez : « Cette voiture est plus chère ___ celle de mon frère. »', 'Dans une comparaison avec un nom ou un pronom, on utilise « que » : plus chère que celle de mon frère.', 'struct_comparatif_que'),
    ('q12', 'Complétez : « Il travaille dans cette entreprise ___ 2020. »', 'Pour une situation commencée dans le passé et encore vraie au présent, on utilise « depuis » avec une date ou une durée.', 'struct_depuis_date'),
    ('q13', 'Remplacez le complément : « Elle a acheté des pommes. → Elle ___ a acheté. »', '« Des pommes » exprime une quantité indéterminée. Le pronom « en » remplace ce type de complément.', 'struct_pronom_en_quantite'),
    ('q14', 'Complétez : « Il faut que nous ___ à l’heure demain. »', 'Après « il faut que », on utilise le subjonctif. Pour « être » avec « nous », la forme est « soyons ».', 'struct_subjonctif_il_faut_nous'),
    ('q15', 'Complétez : « Le dossier ___ par le directeur ce matin. »', 'À la voix passive au passé composé, on utilise « a été » + participe passé. « Dossier » est masculin singulier : « signé ».', 'struct_passif_passe_compose'),
    ('q16', 'Complétez : « Je te téléphonerai dès que je ___. »', 'Après « dès que », pour une action future considérée comme accomplie avant l’action principale, on utilise le futur antérieur : « serai arrivé ».', 'struct_futur_anterieur_des_que'),
    ('q17', 'Complétez : « Elle parle français ___ facilement qu’avant. »', 'On compare deux degrés d’une même qualité : « plus facilement qu’avant ».', 'struct_comparatif_adverbe'),
    ('q18', 'Complétez : « J’ai besoin ___ ton aide pour finir ce travail. »', 'L’expression correcte est « avoir besoin de ». Devant « ton aide », on garde « de ».', 'struct_preposition_besoin_de'),
    ('q19', 'Complétez : « Elle est arrivée en retard, ___ elle avait prévenu son responsable. »', '« Cependant » exprime une opposition ou une nuance entre deux informations.', 'struct_connecteur_opposition'),
    ('q20', 'Complétez : « C’est le village ___ je suis né. »', 'Pour un lieu, le pronom relatif correct est « où ».', 'struct_relatif_ou_lieu'),
    ('q21', 'Complétez : « Je voudrais que vous ___ ce formulaire avant lundi. »', '« Je voudrais que » exprime un souhait et demande le subjonctif : « remplissiez ».', 'struct_subjonctif_souhait_vous'),
    ('q22', 'Complétez : « En ___ plus tôt, tu aurais évité les embouteillages. »', 'Le gérondif se forme avec « en + participe présent ». Pour partir : « en partant ».', 'struct_gerondif_partant'),
    ('q23', 'Complétez : « Ce livre est ___ intéressant que le précédent. »', 'Pour exprimer l’égalité, on utilise « aussi + adjectif + que ».', 'struct_comparatif_egalite'),
    ('q24', 'Complétez : « Elle m’a demandé ___ je pouvais l’aider. »', 'Au discours indirect, une question fermée est introduite par « si ».', 'struct_discours_indirect_question_fermee'),
    ('q25', 'Complétez : « Malgré la pluie, nous ___ sortis nous promener. »', 'Le verbe « sortir » se conjugue ici avec l’auxiliaire « être » au passé composé : « sommes sortis ».', 'struct_passe_compose_aux_etre'),
    ('q26', 'Complétez : « Il n’a pas pu venir ___ panne de voiture. »', '« À cause de » introduit une cause négative ou un problème. La panne explique son absence.', 'struct_cause_a_cause_de'),
    ('q27', 'Complétez : « Tu devrais parler moins vite pour que tout le monde te ___. »', '« Pour que » est suivi du subjonctif. Avec « comprendre » : « comprenne ».', 'struct_subjonctif_pour_que'),
    ('q28', 'Complétez : « Les documents que j’ai ___ sont sur ton bureau. »', 'Avec l’auxiliaire avoir, le participe passé s’accorde avec le COD placé avant le verbe. « Que » reprend « les documents », masculin pluriel : « préparés ».', 'struct_accord_participe_avoir_cod'),
    ('q29', 'Complétez : « Il est interdit ___ fumer dans ce bâtiment. »', 'La construction correcte est « il est interdit de + infinitif ».', 'struct_interdit_de_infinitif'),
    ('q30', 'Complétez : « Je connais bien la ville ___ tu vas t’installer. »', 'Le verbe « s’installer » se construit avec un complément de lieu. Pour un lieu, on utilise « où ».', 'struct_relatif_ou_installation')
), inserted_questions AS (
  INSERT INTO questions
    (id, module, theme_id, passage_id, media_id, difficulty, question_type, statement, explanation,
     is_active, created_at, updated_at, status, tcf_sub_theme, audio_mode, competence_code)
  SELECT
    gen_random_uuid(),
    'TCF',
    '22222222-0000-0000-0000-000000000003',
    NULL,
    NULL,
    'B1',
    'STRUCTURE',
    statement,
    explanation,
    true,
    now(),
    now(),
    'ACTIVE',
    NULL,
    NULL,
    competence_code
  FROM qdata
  RETURNING id, competence_code
), cdata(competence_code, label, is_correct, display_order) AS (
  VALUES
    ('struct_si_imparfait_conditionnel', 'achète', false, 1),
    ('struct_si_imparfait_conditionnel', 'achèterai', false, 2),
    ('struct_si_imparfait_conditionnel', 'achèterais', true, 3),
    ('struct_si_imparfait_conditionnel', 'ai acheté', false, 4),
    ('struct_relatif_dont_personne', 'qui', false, 1),
    ('struct_relatif_dont_personne', 'que', false, 2),
    ('struct_relatif_dont_personne', 'dont', true, 3),
    ('struct_relatif_dont_personne', 'où', false, 4),
    ('struct_plus_que_parfait_anterieur', 'oublie', false, 1),
    ('struct_plus_que_parfait_anterieur', 'a oublié', false, 2),
    ('struct_plus_que_parfait_anterieur', 'avait oublié', true, 3),
    ('struct_plus_que_parfait_anterieur', 'oubliera', false, 4),
    ('struct_pronom_y_idee', 'en', false, 1),
    ('struct_pronom_y_idee', 'y', true, 2),
    ('struct_pronom_y_idee', 'les', false, 3),
    ('struct_pronom_y_idee', 'leur', false, 4),
    ('struct_subjonctif_bien_que', 'est', false, 1),
    ('struct_subjonctif_bien_que', 'sera', false, 2),
    ('struct_subjonctif_bien_que', 'soit', true, 3),
    ('struct_subjonctif_bien_que', 'était', false, 4),
    ('struct_connecteur_cause', 'donc', false, 1),
    ('struct_connecteur_cause', 'mais', false, 2),
    ('struct_connecteur_cause', 'parce qu’', true, 3),
    ('struct_connecteur_cause', 'pourtant', false, 4),
    ('struct_discours_indirect_affirmation', 'Il dit s’il est malade', false, 1),
    ('struct_discours_indirect_affirmation', 'Il dit qu’il est malade', true, 2),
    ('struct_discours_indirect_affirmation', 'Il dit quand il est malade', false, 3),
    ('struct_discours_indirect_affirmation', 'Il dit pourquoi il est malade', false, 4),
    ('struct_relatif_qui_indicatif', 'peut', true, 1),
    ('struct_relatif_qui_indicatif', 'puisse', false, 2),
    ('struct_relatif_qui_indicatif', 'pourrait', false, 3),
    ('struct_relatif_qui_indicatif', 'pouvait', false, 4),
    ('struct_preposition_sans_infinitif', 'dit', false, 1),
    ('struct_preposition_sans_infinitif', 'dire', true, 2),
    ('struct_preposition_sans_infinitif', 'disant', false, 3),
    ('struct_preposition_sans_infinitif', 'dira', false, 4),
    ('struct_interrogatif_pourquoi', 'où', false, 1),
    ('struct_interrogatif_pourquoi', 'comment', false, 2),
    ('struct_interrogatif_pourquoi', 'pourquoi', true, 3),
    ('struct_interrogatif_pourquoi', 'combien', false, 4),
    ('struct_comparatif_que', 'comme', false, 1),
    ('struct_comparatif_que', 'que', true, 2),
    ('struct_comparatif_que', 'de', false, 3),
    ('struct_comparatif_que', 'à', false, 4),
    ('struct_depuis_date', 'pendant', false, 1),
    ('struct_depuis_date', 'il y a', false, 2),
    ('struct_depuis_date', 'depuis', true, 3),
    ('struct_depuis_date', 'pour', false, 4),
    ('struct_pronom_en_quantite', 'les', false, 1),
    ('struct_pronom_en_quantite', 'en', true, 2),
    ('struct_pronom_en_quantite', 'y', false, 3),
    ('struct_pronom_en_quantite', 'leur', false, 4),
    ('struct_subjonctif_il_faut_nous', 'sommes', false, 1),
    ('struct_subjonctif_il_faut_nous', 'serons', false, 2),
    ('struct_subjonctif_il_faut_nous', 'soyons', true, 3),
    ('struct_subjonctif_il_faut_nous', 'étions', false, 4),
    ('struct_passif_passe_compose', 'a signé', false, 1),
    ('struct_passif_passe_compose', 'a été signé', true, 2),
    ('struct_passif_passe_compose', 'est signant', false, 3),
    ('struct_passif_passe_compose', 'sera signer', false, 4),
    ('struct_futur_anterieur_des_que', 'suis arrivé', false, 1),
    ('struct_futur_anterieur_des_que', 'arrive', false, 2),
    ('struct_futur_anterieur_des_que', 'serai arrivé', true, 3),
    ('struct_futur_anterieur_des_que', 'arriverais', false, 4),
    ('struct_comparatif_adverbe', 'plus', true, 1),
    ('struct_comparatif_adverbe', 'très', false, 2),
    ('struct_comparatif_adverbe', 'beaucoup', false, 3),
    ('struct_comparatif_adverbe', 'mieux', false, 4),
    ('struct_preposition_besoin_de', 'à', false, 1),
    ('struct_preposition_besoin_de', 'de', true, 2),
    ('struct_preposition_besoin_de', 'pour', false, 3),
    ('struct_preposition_besoin_de', 'avec', false, 4),
    ('struct_connecteur_opposition', 'donc', false, 1),
    ('struct_connecteur_opposition', 'cependant', true, 2),
    ('struct_connecteur_opposition', 'parce que', false, 3),
    ('struct_connecteur_opposition', 'afin que', false, 4),
    ('struct_relatif_ou_lieu', 'que', false, 1),
    ('struct_relatif_ou_lieu', 'dont', false, 2),
    ('struct_relatif_ou_lieu', 'où', true, 3),
    ('struct_relatif_ou_lieu', 'qui', false, 4),
    ('struct_subjonctif_souhait_vous', 'remplissez', false, 1),
    ('struct_subjonctif_souhait_vous', 'remplirez', false, 2),
    ('struct_subjonctif_souhait_vous', 'remplissiez', true, 3),
    ('struct_subjonctif_souhait_vous', 'rempliriez', false, 4),
    ('struct_gerondif_partant', 'pars', false, 1),
    ('struct_gerondif_partant', 'partir', false, 2),
    ('struct_gerondif_partant', 'partant', true, 3),
    ('struct_gerondif_partant', 'parti', false, 4),
    ('struct_comparatif_egalite', 'autant', false, 1),
    ('struct_comparatif_egalite', 'aussi', true, 2),
    ('struct_comparatif_egalite', 'tellement', false, 3),
    ('struct_comparatif_egalite', 'si', false, 4),
    ('struct_discours_indirect_question_fermee', 'que', false, 1),
    ('struct_discours_indirect_question_fermee', 'si', true, 2),
    ('struct_discours_indirect_question_fermee', 'où', false, 3),
    ('struct_discours_indirect_question_fermee', 'dont', false, 4),
    ('struct_passe_compose_aux_etre', 'avons', false, 1),
    ('struct_passe_compose_aux_etre', 'sommes', true, 2),
    ('struct_passe_compose_aux_etre', 'étions', false, 3),
    ('struct_passe_compose_aux_etre', 'serons', false, 4),
    ('struct_cause_a_cause_de', 'grâce à une', false, 1),
    ('struct_cause_a_cause_de', 'à cause d’une', true, 2),
    ('struct_cause_a_cause_de', 'malgré une', false, 3),
    ('struct_cause_a_cause_de', 'afin d’une', false, 4),
    ('struct_subjonctif_pour_que', 'comprend', false, 1),
    ('struct_subjonctif_pour_que', 'comprendra', false, 2),
    ('struct_subjonctif_pour_que', 'comprenne', true, 3),
    ('struct_subjonctif_pour_que', 'comprendrait', false, 4),
    ('struct_accord_participe_avoir_cod', 'préparé', false, 1),
    ('struct_accord_participe_avoir_cod', 'préparés', true, 2),
    ('struct_accord_participe_avoir_cod', 'préparées', false, 3),
    ('struct_accord_participe_avoir_cod', 'préparer', false, 4),
    ('struct_interdit_de_infinitif', 'à', false, 1),
    ('struct_interdit_de_infinitif', 'de', true, 2),
    ('struct_interdit_de_infinitif', 'pour', false, 3),
    ('struct_interdit_de_infinitif', 'en', false, 4),
    ('struct_relatif_ou_installation', 'dont', false, 1),
    ('struct_relatif_ou_installation', 'que', false, 2),
    ('struct_relatif_ou_installation', 'où', true, 3),
    ('struct_relatif_ou_installation', 'qui', false, 4)
)
INSERT INTO choices
  (id, question_id, label, is_correct, display_order)
SELECT
  gen_random_uuid(),
  iq.id,
  cd.label,
  cd.is_correct,
  cd.display_order
FROM cdata cd
JOIN inserted_questions iq ON iq.competence_code = cd.competence_code;
