-- ============================================================================
-- V633 — TCF Structure B1
-- ----------------------------------------------------------------------------
-- 30 questions de structure niveau B1.
-- IDs générés avec gen_random_uuid().
-- ============================================================================

WITH qdata(q_ref, statement, explanation, competence_code) AS (
  VALUES
    ('q01', 'Complétez : « Si tu étais plus disponible, nous ___ plus souvent. »', 'Avec « si + imparfait », la proposition principale se met au conditionnel présent : « sortirions ».', 'struct_b1_v633_si_imparfait_conditionnel'),
    ('q02', 'Complétez : « Voilà le collègue ___ j’ai reçu le message ce matin. »', 'Quand le complément est introduit par « de » — recevoir un message de quelqu’un — on utilise le pronom relatif « dont ».', 'struct_b1_v633_relatif_dont'),
    ('q03', 'Complétez : « Quand je suis arrivé, le film ___ déjà commencé. »', 'Le plus-que-parfait marque une action antérieure à une autre action passée : « avait déjà commencé ».', 'struct_b1_v633_plus_que_parfait'),
    ('q04', 'Remplacez le complément : « Elle répond à cette question. → Elle ___ répond. »', 'Le pronom « y » remplace souvent un complément introduit par « à » quand il s’agit d’une chose ou d’une idée.', 'struct_b1_v633_pronom_y'),
    ('q05', 'Complétez : « Il faut que tu ___ plus attention aux détails. »', 'Après « il faut que », on emploie le subjonctif : « fasses ».', 'struct_b1_v633_subjonctif_faire'),
    ('q06', 'Complétez : « Je suis resté chez moi ___ j’étais malade. »', 'On exprime ici la cause. « Comme » placé en début de proposition donne la raison.', 'struct_b1_v633_connecteur_cause'),
    ('q07', 'Transformez au discours indirect : Elle dit : « Je viendrai demain. »', 'Au discours indirect, on introduit l’affirmation avec « que ». Ici, le verbe introducteur est au présent, donc le futur reste possible.', 'struct_b1_v633_discours_indirect_futur'),
    ('q08', 'Complétez : « Je cherche un appartement qui ___ près du métro. »', 'On emploie ici le subjonctif après « chercher » car l’appartement est souhaité mais pas encore identifié.', 'struct_b1_v633_subjonctif_relatif'),
    ('q09', 'Complétez : « Après ___ le dossier, vous pourrez signer le contrat. »', 'Après « après », on utilise souvent l’infinitif passé pour indiquer une action terminée avant une autre : « avoir lu ».', 'struct_b1_v633_apres_infinitif_passe'),
    ('q10', 'Complétez : « Je ne sais pas ___ il a mis les clés. »', 'On cherche un lieu. L’adverbe interrogatif correct est « où ».', 'struct_b1_v633_interrogatif_ou'),
    ('q11', 'Complétez : « Cette solution est moins compliquée ___ l’autre. »', 'Dans une comparaison d’infériorité, on utilise « moins + adjectif + que ».', 'struct_b1_v633_comparatif_moins_que'),
    ('q12', 'Complétez : « Nous habitons dans ce quartier ___ trois ans. »', 'Pour une situation commencée dans le passé et encore vraie, on utilise « depuis ».', 'struct_b1_v633_depuis_duree'),
    ('q13', 'Remplacez le complément : « Il parle de son projet. → Il ___ parle souvent. »', 'Le pronom « en » remplace un complément introduit par « de », surtout pour une chose ou une idée.', 'struct_b1_v633_pronom_en'),
    ('q14', 'Complétez : « Bien que la situation ___ difficile, ils restent optimistes. »', '« Bien que » est suivi du subjonctif. Avec « être », on dit : « soit ».', 'struct_b1_v633_bien_que_subjonctif'),
    ('q15', 'Complétez : « Les invitations ___ envoyées hier soir. »', 'À la voix passive au passé composé, on utilise « ont été » + participe passé. « Invitations » est féminin pluriel : « envoyées ».', 'struct_b1_v633_passif_passe_compose'),
    ('q16', 'Complétez : « Je partirai dès que tu ___ prêt. »', 'Après « dès que », le futur simple est utilisé pour une action future : « seras ».', 'struct_b1_v633_des_que_futur'),
    ('q17', 'Complétez : « Elle conduit ___ prudemment que son frère. »', 'Pour comparer deux manières de faire, on utilise « plus + adverbe + que ».', 'struct_b1_v633_comparatif_adverbe'),
    ('q18', 'Complétez : « Il a du mal ___ comprendre les consignes. »', 'L’expression correcte est « avoir du mal à + infinitif ».', 'struct_b1_v633_avoir_du_mal_a'),
    ('q19', 'Complétez : « Il faisait froid ; ___, nous avons décidé de marcher. »', '« Pourtant » exprime une opposition entre deux idées.', 'struct_b1_v633_connecteur_opposition'),
    ('q20', 'Complétez : « Le jour ___ nous sommes partis, il pleuvait beaucoup. »', 'Pour exprimer un moment, on utilise le pronom relatif « où ».', 'struct_b1_v633_relatif_ou_temps'),
    ('q21', 'Complétez : « Je souhaite que vous ___ cette réponse avant midi. »', 'Après « souhaiter que », on emploie le subjonctif : « envoyiez ».', 'struct_b1_v633_subjonctif_envoyer'),
    ('q22', 'Complétez : « En ___ régulièrement, tu progresseras rapidement. »', 'Le gérondif se forme avec « en + participe présent » : « en pratiquant ».', 'struct_b1_v633_gerondif'),
    ('q23', 'Complétez : « Il y avait ___ de monde que la semaine dernière. »', 'Pour comparer une quantité supérieure, on utilise « plus de ... que ».', 'struct_b1_v633_quantite_plus_de'),
    ('q24', 'Complétez : « Elle m’a demandé ___ j’avais terminé le rapport. »', 'Au discours indirect, une question fermée est introduite par « si ».', 'struct_b1_v633_indirect_si'),
    ('q25', 'Complétez : « Nous nous ___ levés très tôt ce matin. »', 'Au passé composé des verbes pronominaux, on utilise l’auxiliaire « être » : « nous nous sommes levés ».', 'struct_b1_v633_pronominal_passe_compose'),
    ('q26', 'Complétez : « Il a réussi ___ à son sérieux. »', '« Grâce à » exprime une cause positive.', 'struct_b1_v633_grace_a'),
    ('q27', 'Complétez : « Je t’explique la règle pour que tu la ___. »', '« Pour que » est suivi du subjonctif : « comprennes ».', 'struct_b1_v633_pour_que_subjonctif'),
    ('q28', 'Complétez : « La lettre que j’ai ___ ce matin est importante. »', 'Avec l’auxiliaire avoir, le participe passé s’accorde avec le COD placé avant le verbe. « Lettre » est féminin singulier : « reçue ».', 'struct_b1_v633_accord_cod_avant'),
    ('q29', 'Complétez : « Il est nécessaire ___ prévenir le responsable. »', 'La construction correcte est « il est nécessaire de + infinitif ».', 'struct_b1_v633_necessaire_de'),
    ('q30', 'Complétez : « C’est une décision ___ je ne suis pas d’accord. »', 'Avec l’expression « être d’accord avec », le pronom relatif correct est « avec laquelle » pour « une décision ».', 'struct_b1_v633_relatif_avec_laquelle')
), inserted_questions AS (
  INSERT INTO questions
    (id, module, theme_id, passage_id, media_id, difficulty, question_type, statement, explanation,
     is_active, created_at, updated_at, status, tcf_sub_theme, audio_mode, competence_code)
  SELECT
    gen_random_uuid(),
    'TCF',
    '22222222-0000-0000-0000-000000000003',
    NULL,
    NULL,
    'B1',
    'STRUCTURE',
    statement,
    explanation,
    true,
    now(),
    now(),
    'ACTIVE',
    NULL,
    NULL,
    competence_code
  FROM qdata
  RETURNING id, competence_code
), cdata(competence_code, label, is_correct, display_order) AS (
  VALUES
    ('struct_b1_v633_si_imparfait_conditionnel', 'sortons', false, 1),
    ('struct_b1_v633_si_imparfait_conditionnel', 'sortirons', false, 2),
    ('struct_b1_v633_si_imparfait_conditionnel', 'sortirions', true, 3),
    ('struct_b1_v633_si_imparfait_conditionnel', 'sommes sortis', false, 4),
    ('struct_b1_v633_relatif_dont', 'que', false, 1),
    ('struct_b1_v633_relatif_dont', 'dont', true, 2),
    ('struct_b1_v633_relatif_dont', 'où', false, 3),
    ('struct_b1_v633_relatif_dont', 'qui', false, 4),
    ('struct_b1_v633_plus_que_parfait', 'commence', false, 1),
    ('struct_b1_v633_plus_que_parfait', 'a commencé', false, 2),
    ('struct_b1_v633_plus_que_parfait', 'avait commencé', true, 3),
    ('struct_b1_v633_plus_que_parfait', 'commencera', false, 4),
    ('struct_b1_v633_pronom_y', 'en', false, 1),
    ('struct_b1_v633_pronom_y', 'la', false, 2),
    ('struct_b1_v633_pronom_y', 'y', true, 3),
    ('struct_b1_v633_pronom_y', 'lui', false, 4),
    ('struct_b1_v633_subjonctif_faire', 'fais', false, 1),
    ('struct_b1_v633_subjonctif_faire', 'feras', false, 2),
    ('struct_b1_v633_subjonctif_faire', 'fasses', true, 3),
    ('struct_b1_v633_subjonctif_faire', 'faisais', false, 4),
    ('struct_b1_v633_connecteur_cause', 'mais', false, 1),
    ('struct_b1_v633_connecteur_cause', 'comme', true, 2),
    ('struct_b1_v633_connecteur_cause', 'pourtant', false, 3),
    ('struct_b1_v633_connecteur_cause', 'donc', false, 4),
    ('struct_b1_v633_discours_indirect_futur', 'Elle dit si elle viendra demain', false, 1),
    ('struct_b1_v633_discours_indirect_futur', 'Elle dit qu’elle viendra demain', true, 2),
    ('struct_b1_v633_discours_indirect_futur', 'Elle dit quand elle viendra demain', false, 3),
    ('struct_b1_v633_discours_indirect_futur', 'Elle dit pourquoi elle viendra demain', false, 4),
    ('struct_b1_v633_subjonctif_relatif', 'est', false, 1),
    ('struct_b1_v633_subjonctif_relatif', 'sera', false, 2),
    ('struct_b1_v633_subjonctif_relatif', 'soit', true, 3),
    ('struct_b1_v633_subjonctif_relatif', 'était', false, 4),
    ('struct_b1_v633_apres_infinitif_passe', 'lire', false, 1),
    ('struct_b1_v633_apres_infinitif_passe', 'avoir lu', true, 2),
    ('struct_b1_v633_apres_infinitif_passe', 'lisant', false, 3),
    ('struct_b1_v633_apres_infinitif_passe', 'lu', false, 4),
    ('struct_b1_v633_interrogatif_ou', 'où', true, 1),
    ('struct_b1_v633_interrogatif_ou', 'quand', false, 2),
    ('struct_b1_v633_interrogatif_ou', 'pourquoi', false, 3),
    ('struct_b1_v633_interrogatif_ou', 'combien', false, 4),
    ('struct_b1_v633_comparatif_moins_que', 'comme', false, 1),
    ('struct_b1_v633_comparatif_moins_que', 'que', true, 2),
    ('struct_b1_v633_comparatif_moins_que', 'de', false, 3),
    ('struct_b1_v633_comparatif_moins_que', 'à', false, 4),
    ('struct_b1_v633_depuis_duree', 'pendant', false, 1),
    ('struct_b1_v633_depuis_duree', 'depuis', true, 2),
    ('struct_b1_v633_depuis_duree', 'il y a', false, 3),
    ('struct_b1_v633_depuis_duree', 'dans', false, 4),
    ('struct_b1_v633_pronom_en', 'y', false, 1),
    ('struct_b1_v633_pronom_en', 'le', false, 2),
    ('struct_b1_v633_pronom_en', 'en', true, 3),
    ('struct_b1_v633_pronom_en', 'lui', false, 4),
    ('struct_b1_v633_bien_que_subjonctif', 'est', false, 1),
    ('struct_b1_v633_bien_que_subjonctif', 'sera', false, 2),
    ('struct_b1_v633_bien_que_subjonctif', 'soit', true, 3),
    ('struct_b1_v633_bien_que_subjonctif', 'était', false, 4),
    ('struct_b1_v633_passif_passe_compose', 'ont envoyé', false, 1),
    ('struct_b1_v633_passif_passe_compose', 'sont envoyées', false, 2),
    ('struct_b1_v633_passif_passe_compose', 'ont été envoyées', true, 3),
    ('struct_b1_v633_passif_passe_compose', 'seront envoyer', false, 4),
    ('struct_b1_v633_des_que_futur', 'es', false, 1),
    ('struct_b1_v633_des_que_futur', 'seras', true, 2),
    ('struct_b1_v633_des_que_futur', 'étais', false, 3),
    ('struct_b1_v633_des_que_futur', 'sois', false, 4),
    ('struct_b1_v633_comparatif_adverbe', 'aussi', false, 1),
    ('struct_b1_v633_comparatif_adverbe', 'plus', true, 2),
    ('struct_b1_v633_comparatif_adverbe', 'très', false, 3),
    ('struct_b1_v633_comparatif_adverbe', 'beaucoup', false, 4),
    ('struct_b1_v633_avoir_du_mal_a', 'de', false, 1),
    ('struct_b1_v633_avoir_du_mal_a', 'à', true, 2),
    ('struct_b1_v633_avoir_du_mal_a', 'pour', false, 3),
    ('struct_b1_v633_avoir_du_mal_a', 'avec', false, 4),
    ('struct_b1_v633_connecteur_opposition', 'pourtant', true, 1),
    ('struct_b1_v633_connecteur_opposition', 'parce que', false, 2),
    ('struct_b1_v633_connecteur_opposition', 'donc', false, 3),
    ('struct_b1_v633_connecteur_opposition', 'afin que', false, 4),
    ('struct_b1_v633_relatif_ou_temps', 'que', false, 1),
    ('struct_b1_v633_relatif_ou_temps', 'dont', false, 2),
    ('struct_b1_v633_relatif_ou_temps', 'où', true, 3),
    ('struct_b1_v633_relatif_ou_temps', 'qui', false, 4),
    ('struct_b1_v633_subjonctif_envoyer', 'envoyez', false, 1),
    ('struct_b1_v633_subjonctif_envoyer', 'enverrez', false, 2),
    ('struct_b1_v633_subjonctif_envoyer', 'envoyiez', true, 3),
    ('struct_b1_v633_subjonctif_envoyer', 'envoyez-vous', false, 4),
    ('struct_b1_v633_gerondif', 'pratique', false, 1),
    ('struct_b1_v633_gerondif', 'pratiquer', false, 2),
    ('struct_b1_v633_gerondif', 'pratiquant', true, 3),
    ('struct_b1_v633_gerondif', 'pratiqué', false, 4),
    ('struct_b1_v633_quantite_plus_de', 'plus', false, 1),
    ('struct_b1_v633_quantite_plus_de', 'plus de', true, 2),
    ('struct_b1_v633_quantite_plus_de', 'aussi', false, 3),
    ('struct_b1_v633_quantite_plus_de', 'moins que', false, 4),
    ('struct_b1_v633_indirect_si', 'que', false, 1),
    ('struct_b1_v633_indirect_si', 'si', true, 2),
    ('struct_b1_v633_indirect_si', 'où', false, 3),
    ('struct_b1_v633_indirect_si', 'dont', false, 4),
    ('struct_b1_v633_pronominal_passe_compose', 'avons', false, 1),
    ('struct_b1_v633_pronominal_passe_compose', 'sommes', true, 2),
    ('struct_b1_v633_pronominal_passe_compose', 'étions', false, 3),
    ('struct_b1_v633_pronominal_passe_compose', 'serons', false, 4),
    ('struct_b1_v633_grace_a', 'à cause de', false, 1),
    ('struct_b1_v633_grace_a', 'grâce', false, 2),
    ('struct_b1_v633_grace_a', 'grâce à', true, 3),
    ('struct_b1_v633_grace_a', 'malgré', false, 4),
    ('struct_b1_v633_pour_que_subjonctif', 'comprends', false, 1),
    ('struct_b1_v633_pour_que_subjonctif', 'comprendras', false, 2),
    ('struct_b1_v633_pour_que_subjonctif', 'comprennes', true, 3),
    ('struct_b1_v633_pour_que_subjonctif', 'comprenais', false, 4),
    ('struct_b1_v633_accord_cod_avant', 'reçu', false, 1),
    ('struct_b1_v633_accord_cod_avant', 'reçue', true, 2),
    ('struct_b1_v633_accord_cod_avant', 'reçus', false, 3),
    ('struct_b1_v633_accord_cod_avant', 'recevoir', false, 4),
    ('struct_b1_v633_necessaire_de', 'à', false, 1),
    ('struct_b1_v633_necessaire_de', 'de', true, 2),
    ('struct_b1_v633_necessaire_de', 'pour', false, 3),
    ('struct_b1_v633_necessaire_de', 'en', false, 4),
    ('struct_b1_v633_relatif_avec_laquelle', 'dont', false, 1),
    ('struct_b1_v633_relatif_avec_laquelle', 'où', false, 2),
    ('struct_b1_v633_relatif_avec_laquelle', 'avec laquelle', true, 3),
    ('struct_b1_v633_relatif_avec_laquelle', 'que', false, 4)
)
INSERT INTO choices
  (id, question_id, label, is_correct, display_order)
SELECT
  gen_random_uuid(),
  iq.id,
  cd.label,
  cd.is_correct,
  cd.display_order
FROM cdata cd
JOIN inserted_questions iq ON iq.competence_code = cd.competence_code;
