-- ============================================================================
-- V634 — TCF Structure B1
-- ----------------------------------------------------------------------------
-- 30 questions de structure niveau B1.
-- IDs générés avec gen_random_uuid().
-- ============================================================================

WITH qdata(q_ref, statement, explanation, competence_code) AS (
  VALUES
    ('q01', 'Complétez : « Si j’avais ton numéro, je t’___ tout de suite. »', 'Avec « si + imparfait », la proposition principale se met au conditionnel présent : « appellerais ».', 'struct_b1_v634_si_imparfait_conditionnel'),
    ('q02', 'Complétez : « C’est la ville ___ je suis né. »', 'Pour indiquer un lieu avec un pronom relatif, on utilise « où ».', 'struct_b1_v634_relatif_ou_lieu'),
    ('q03', 'Complétez : « Quand elle est rentrée, les enfants ___ déjà dîné. »', 'Le plus-que-parfait exprime une action terminée avant une autre action passée : « avaient déjà dîné ».', 'struct_b1_v634_plus_que_parfait'),
    ('q04', 'Remplacez le complément : « Tu penses à tes vacances ? — Oui, j’___ pense souvent. »', 'Le pronom « y » remplace un complément introduit par « à » quand il s’agit d’une chose ou d’une idée.', 'struct_b1_v634_pronom_y'),
    ('q05', 'Complétez : « Il est important que nous ___ à l’heure. »', 'Après « il est important que », on emploie le subjonctif : « soyons ».', 'struct_b1_v634_subjonctif_etre'),
    ('q06', 'Complétez : « ___ il faisait beau, nous avons déjeuné dehors. »', '« Comme » exprime la cause et se place souvent en début de phrase.', 'struct_b1_v634_connecteur_cause'),
    ('q07', 'Transformez au discours indirect : Paul dit : « Je suis fatigué. »', 'Au discours indirect avec un verbe introducteur au présent, on garde le présent : « Paul dit qu’il est fatigué ».', 'struct_b1_v634_discours_indirect_present'),
    ('q08', 'Complétez : « Je cherche quelqu’un qui ___ parler espagnol. »', 'Après « chercher quelqu’un qui », on peut employer le subjonctif quand la personne n’est pas identifiée : « puisse ».', 'struct_b1_v634_subjonctif_relatif'),
    ('q09', 'Complétez : « Avant de ___, éteignez votre téléphone. »', 'Après « avant de », le verbe se met à l’infinitif : « partir ».', 'struct_b1_v634_avant_de_infinitif'),
    ('q10', 'Complétez : « Je me demande ___ elle va accepter cette proposition. »', 'Une question indirecte fermée s’introduit avec « si ».', 'struct_b1_v634_interrogative_indirecte_si'),
    ('q11', 'Complétez : « Ce trajet est aussi long ___ celui d’hier. »', 'La comparaison d’égalité se construit avec « aussi + adjectif + que ».', 'struct_b1_v634_comparatif_aussi_que'),
    ('q12', 'Complétez : « Elle travaille dans cette entreprise ___ 2021. »', 'Pour indiquer le point de départ d’une situation qui continue, on utilise « depuis ».', 'struct_b1_v634_depuis_date'),
    ('q13', 'Remplacez le complément : « Nous avons besoin de ces documents. → Nous ___ avons besoin. »', 'Le pronom « en » remplace un complément introduit par « de ».', 'struct_b1_v634_pronom_en'),
    ('q14', 'Complétez : « Bien qu’il ___ tard, elle continue à travailler. »', '« Bien que » est suivi du subjonctif : « soit ».', 'struct_b1_v634_bien_que_subjonctif'),
    ('q15', 'Complétez : « Les résultats seront ___ demain matin. »', 'À la voix passive au futur, on utilise « seront » + participe passé. Avec « résultats », masculin pluriel : « publiés ».', 'struct_b1_v634_passif_futur'),
    ('q16', 'Complétez : « Je te téléphonerai dès que je ___ chez moi. »', 'Après « dès que » pour une action future, on emploie le futur simple : « serai ».', 'struct_b1_v634_des_que_futur'),
    ('q17', 'Complétez : « Elle parle français ___ couramment que moi. »', 'On compare ici une manière de parler : « plus + adverbe + que ».', 'struct_b1_v634_comparatif_adverbe'),
    ('q18', 'Complétez : « Il a réussi ___ finir le dossier avant midi. »', 'L’expression correcte est « réussir à + infinitif ».', 'struct_b1_v634_reussir_a'),
    ('q19', 'Complétez : « Il était très occupé ; ___, il a trouvé le temps de m’aider. »', '« Pourtant » exprime une opposition entre deux idées.', 'struct_b1_v634_connecteur_opposition'),
    ('q20', 'Complétez : « Le restaurant ___ nous avons mangé était excellent. »', 'Pour parler d’un lieu, on utilise le pronom relatif « où ».', 'struct_b1_v634_relatif_ou_lieu2'),
    ('q21', 'Complétez : « Je préfère que vous ___ directement le responsable. »', 'Après « préférer que », on emploie le subjonctif : « contactiez ».', 'struct_b1_v634_subjonctif_contacter'),
    ('q22', 'Complétez : « En ___ le plan, vous trouverez facilement l’adresse. »', 'Le gérondif se forme avec « en + participe présent » : « suivant ».', 'struct_b1_v634_gerondif'),
    ('q23', 'Complétez : « Il y a autant ___ participants que l’année dernière. »', 'Pour exprimer une quantité égale, on utilise « autant de ... que ».', 'struct_b1_v634_quantite_autant_de'),
    ('q24', 'Complétez : « Elle m’a expliqué ___ elle avait changé de travail. »', 'On demande ici la raison. Le mot interrogatif indirect correct est « pourquoi ».', 'struct_b1_v634_indirect_pourquoi'),
    ('q25', 'Complétez : « Ils se ___ rencontrés pendant leurs études. »', 'Au passé composé des verbes pronominaux, on utilise l’auxiliaire « être » : « se sont rencontrés ».', 'struct_b1_v634_pronominal_passe_compose'),
    ('q26', 'Complétez : « À cause ___ la grève, le train est annulé. »', 'La locution correcte est « à cause de ».', 'struct_b1_v634_a_cause_de'),
    ('q27', 'Complétez : « Je parle lentement afin que tout le monde me ___. »', '« Afin que » est suivi du subjonctif : « comprenne ».', 'struct_b1_v634_afin_que_subjonctif'),
    ('q28', 'Complétez : « Les photos que j’ai ___ hier sont magnifiques. »', 'Avec l’auxiliaire avoir, le participe passé s’accorde avec le COD placé avant. « Photos » est féminin pluriel : « prises ».', 'struct_b1_v634_accord_cod_avant'),
    ('q29', 'Complétez : « Il est interdit ___ fumer dans cette salle. »', 'La construction correcte est « il est interdit de + infinitif ».', 'struct_b1_v634_interdit_de'),
    ('q30', 'Complétez : « C’est un sujet ___ nous devons réfléchir sérieusement. »', 'Le verbe « réfléchir » se construit avec « à ». Avec un pronom relatif pour une chose, on utilise « auquel ».', 'struct_b1_v634_relatif_auquel')
), inserted_questions AS (
  INSERT INTO questions
    (id, module, theme_id, passage_id, media_id, difficulty, question_type, statement, explanation,
     is_active, created_at, updated_at, status, tcf_sub_theme, audio_mode, competence_code)
  SELECT
    gen_random_uuid(),
    'TCF',
    '22222222-0000-0000-0000-000000000003',
    NULL,
    NULL,
    'B1',
    'STRUCTURE',
    statement,
    explanation,
    true,
    now(),
    now(),
    'ACTIVE',
    NULL,
    NULL,
    competence_code
  FROM qdata
  RETURNING id, competence_code
), cdata(competence_code, label, is_correct, display_order) AS (
  VALUES
    ('struct_b1_v634_si_imparfait_conditionnel', 'appelle', false, 1),
    ('struct_b1_v634_si_imparfait_conditionnel', 'appellerai', false, 2),
    ('struct_b1_v634_si_imparfait_conditionnel', 'appellerais', true, 3),
    ('struct_b1_v634_si_imparfait_conditionnel', 'appelais', false, 4),
    ('struct_b1_v634_relatif_ou_lieu', 'que', false, 1),
    ('struct_b1_v634_relatif_ou_lieu', 'dont', false, 2),
    ('struct_b1_v634_relatif_ou_lieu', 'où', true, 3),
    ('struct_b1_v634_relatif_ou_lieu', 'qui', false, 4),
    ('struct_b1_v634_plus_que_parfait', 'ont', false, 1),
    ('struct_b1_v634_plus_que_parfait', 'avaient', true, 2),
    ('struct_b1_v634_plus_que_parfait', 'auront', false, 3),
    ('struct_b1_v634_plus_que_parfait', 'avaient été', false, 4),
    ('struct_b1_v634_pronom_y', 'en', false, 1),
    ('struct_b1_v634_pronom_y', 'y', true, 2),
    ('struct_b1_v634_pronom_y', 'le', false, 3),
    ('struct_b1_v634_pronom_y', 'lui', false, 4),
    ('struct_b1_v634_subjonctif_etre', 'sommes', false, 1),
    ('struct_b1_v634_subjonctif_etre', 'serons', false, 2),
    ('struct_b1_v634_subjonctif_etre', 'soyons', true, 3),
    ('struct_b1_v634_subjonctif_etre', 'étions', false, 4),
    ('struct_b1_v634_connecteur_cause', 'Comme', true, 1),
    ('struct_b1_v634_connecteur_cause', 'Pourtant', false, 2),
    ('struct_b1_v634_connecteur_cause', 'Donc', false, 3),
    ('struct_b1_v634_connecteur_cause', 'Mais', false, 4),
    ('struct_b1_v634_discours_indirect_present', 'Paul dit qu’il est fatigué.', true, 1),
    ('struct_b1_v634_discours_indirect_present', 'Paul dit il est fatigué.', false, 2),
    ('struct_b1_v634_discours_indirect_present', 'Paul dit qu’il était fatigué.', false, 3),
    ('struct_b1_v634_discours_indirect_present', 'Paul dit de je suis fatigué.', false, 4),
    ('struct_b1_v634_subjonctif_relatif', 'peut', false, 1),
    ('struct_b1_v634_subjonctif_relatif', 'pourra', false, 2),
    ('struct_b1_v634_subjonctif_relatif', 'puisse', true, 3),
    ('struct_b1_v634_subjonctif_relatif', 'pouvait', false, 4),
    ('struct_b1_v634_avant_de_infinitif', 'partir', true, 1),
    ('struct_b1_v634_avant_de_infinitif', 'parti', false, 2),
    ('struct_b1_v634_avant_de_infinitif', 'partez', false, 3),
    ('struct_b1_v634_avant_de_infinitif', 'partira', false, 4),
    ('struct_b1_v634_interrogative_indirecte_si', 'que', false, 1),
    ('struct_b1_v634_interrogative_indirecte_si', 'si', true, 2),
    ('struct_b1_v634_interrogative_indirecte_si', 'où', false, 3),
    ('struct_b1_v634_interrogative_indirecte_si', 'dont', false, 4),
    ('struct_b1_v634_comparatif_aussi_que', 'que', true, 1),
    ('struct_b1_v634_comparatif_aussi_que', 'comme', false, 2),
    ('struct_b1_v634_comparatif_aussi_que', 'de', false, 3),
    ('struct_b1_v634_comparatif_aussi_que', 'à', false, 4),
    ('struct_b1_v634_depuis_date', 'pendant', false, 1),
    ('struct_b1_v634_depuis_date', 'depuis', true, 2),
    ('struct_b1_v634_depuis_date', 'il y a', false, 3),
    ('struct_b1_v634_depuis_date', 'dans', false, 4),
    ('struct_b1_v634_pronom_en', 'y', false, 1),
    ('struct_b1_v634_pronom_en', 'les', false, 2),
    ('struct_b1_v634_pronom_en', 'en', true, 3),
    ('struct_b1_v634_pronom_en', 'leur', false, 4),
    ('struct_b1_v634_bien_que_subjonctif', 'est', false, 1),
    ('struct_b1_v634_bien_que_subjonctif', 'sera', false, 2),
    ('struct_b1_v634_bien_que_subjonctif', 'soit', true, 3),
    ('struct_b1_v634_bien_que_subjonctif', 'était', false, 4),
    ('struct_b1_v634_passif_futur', 'publié', false, 1),
    ('struct_b1_v634_passif_futur', 'publiés', true, 2),
    ('struct_b1_v634_passif_futur', 'publier', false, 3),
    ('struct_b1_v634_passif_futur', 'publiaient', false, 4),
    ('struct_b1_v634_des_que_futur', 'suis', false, 1),
    ('struct_b1_v634_des_que_futur', 'serai', true, 2),
    ('struct_b1_v634_des_que_futur', 'étais', false, 3),
    ('struct_b1_v634_des_que_futur', 'sois', false, 4),
    ('struct_b1_v634_comparatif_adverbe', 'plus', true, 1),
    ('struct_b1_v634_comparatif_adverbe', 'beaucoup', false, 2),
    ('struct_b1_v634_comparatif_adverbe', 'très', false, 3),
    ('struct_b1_v634_comparatif_adverbe', 'autant', false, 4),
    ('struct_b1_v634_reussir_a', 'de', false, 1),
    ('struct_b1_v634_reussir_a', 'à', true, 2),
    ('struct_b1_v634_reussir_a', 'pour', false, 3),
    ('struct_b1_v634_reussir_a', 'en', false, 4),
    ('struct_b1_v634_connecteur_opposition', 'donc', false, 1),
    ('struct_b1_v634_connecteur_opposition', 'car', false, 2),
    ('struct_b1_v634_connecteur_opposition', 'pourtant', true, 3),
    ('struct_b1_v634_connecteur_opposition', 'ainsi', false, 4),
    ('struct_b1_v634_relatif_ou_lieu2', 'où', true, 1),
    ('struct_b1_v634_relatif_ou_lieu2', 'que', false, 2),
    ('struct_b1_v634_relatif_ou_lieu2', 'dont', false, 3),
    ('struct_b1_v634_relatif_ou_lieu2', 'qui', false, 4),
    ('struct_b1_v634_subjonctif_contacter', 'contactez', false, 1),
    ('struct_b1_v634_subjonctif_contacter', 'contactiez', true, 2),
    ('struct_b1_v634_subjonctif_contacter', 'contacterez', false, 3),
    ('struct_b1_v634_subjonctif_contacter', 'contactiez-vous', false, 4),
    ('struct_b1_v634_gerondif', 'suivant', true, 1),
    ('struct_b1_v634_gerondif', 'suivi', false, 2),
    ('struct_b1_v634_gerondif', 'suivre', false, 3),
    ('struct_b1_v634_gerondif', 'suivez', false, 4),
    ('struct_b1_v634_quantite_autant_de', 'de', true, 1),
    ('struct_b1_v634_quantite_autant_de', 'des', false, 2),
    ('struct_b1_v634_quantite_autant_de', 'que', false, 3),
    ('struct_b1_v634_quantite_autant_de', 'à', false, 4),
    ('struct_b1_v634_indirect_pourquoi', 'pourquoi', true, 1),
    ('struct_b1_v634_indirect_pourquoi', 'si', false, 2),
    ('struct_b1_v634_indirect_pourquoi', 'que', false, 3),
    ('struct_b1_v634_indirect_pourquoi', 'dont', false, 4),
    ('struct_b1_v634_pronominal_passe_compose', 'sont', true, 1),
    ('struct_b1_v634_pronominal_passe_compose', 'ont', false, 2),
    ('struct_b1_v634_pronominal_passe_compose', 'étaient', false, 3),
    ('struct_b1_v634_pronominal_passe_compose', 'seront', false, 4),
    ('struct_b1_v634_a_cause_de', 'à', false, 1),
    ('struct_b1_v634_a_cause_de', 'de', true, 2),
    ('struct_b1_v634_a_cause_de', 'pour', false, 3),
    ('struct_b1_v634_a_cause_de', 'par', false, 4),
    ('struct_b1_v634_afin_que_subjonctif', 'comprend', false, 1),
    ('struct_b1_v634_afin_que_subjonctif', 'comprendra', false, 2),
    ('struct_b1_v634_afin_que_subjonctif', 'comprenne', true, 3),
    ('struct_b1_v634_afin_que_subjonctif', 'comprenait', false, 4),
    ('struct_b1_v634_accord_cod_avant', 'pris', false, 1),
    ('struct_b1_v634_accord_cod_avant', 'prise', false, 2),
    ('struct_b1_v634_accord_cod_avant', 'prises', true, 3),
    ('struct_b1_v634_accord_cod_avant', 'prendre', false, 4),
    ('struct_b1_v634_interdit_de', 'à', false, 1),
    ('struct_b1_v634_interdit_de', 'de', true, 2),
    ('struct_b1_v634_interdit_de', 'pour', false, 3),
    ('struct_b1_v634_interdit_de', 'en', false, 4),
    ('struct_b1_v634_relatif_auquel', 'dont', false, 1),
    ('struct_b1_v634_relatif_auquel', 'auquel', true, 2),
    ('struct_b1_v634_relatif_auquel', 'où', false, 3),
    ('struct_b1_v634_relatif_auquel', 'que', false, 4)
)
INSERT INTO choices
  (id, question_id, label, is_correct, display_order)
SELECT
  gen_random_uuid(),
  iq.id,
  cd.label,
  cd.is_correct,
  cd.display_order
FROM cdata cd
JOIN inserted_questions iq ON iq.competence_code = cd.competence_code;
